# dataset
dataset_url: "http://mtg.upf.edu/ismir2004/contest/tempoContest/data1.tar.gz"
label_url: "https://github.com/CPJKU/BallroomAnnotations/archive/master.zip"
dataset_folder: "/homes/yz007/datasets/ballroom/BallroomData/"
label_folder: "/homes/yz007/datasets/ballroom/label/"
spec_folder: "/homes/yz007/datasets/ballroom/spec/"

# model and log
model_folder: "/homes/yz007/models/TCN/"

# create mel spectrogram
fft_size: 2048
hop_length: 0.01
n_mels: 81
sample_rate: 22050
trim_size:
  - 81
  - 3000

# model parameters
input_size:
  - 3000
  - 81
output: 3000
CNN_filters:
  - 16
  - 16
  - 16
CNN_filter_size:
  -
    - 3
    - 3
  -
    - 3
    - 3
  -
    - 1
    - 8
CNN_pool_size:
  -
    - 1
    - 3
  -
    - 1
    - 8
TCN_filters: 16
TCN_kernel_size: 5
dropout: 0.1

# training settings
num_epoch: 100
batch_size: 1
optimizer: 'Adam'
learning_rate: 0.001
k_fold: 8

# CUDA
cuda: True